### ISSUE TITLE
Update authlib dependencies

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-auth-service#43]
When building the backend, the following pip message appears:
```
authlib 1.0.0 requires pytest==5.3.4, but you'll have pytest 6.0.2 which is incompatible.
authlib 1.0.0 requires requests==2.22.0, but you'll have requests 2.24.0 which is incompatible.
```
It seems to have no impact yet, but it would be nice if you could update the dependencies here to sync them with the backend.

**Comment by FinnStutzenstein** [comment]
Done with #45

**Comment by GabrielInTheWorld** [comment]
Done with #45 .

**Comment by jsangmeister** [comment]
The message still persists. I guess it stems from this entry: https://github.com/OpenSlides/openslides-auth-service/blob/b77e9a1dad1bf2a650f6353f2a8583c5e102e98b/auth/libraries/pip-auth/setup.py#L21

**Comment by GabrielInTheWorld** [comment]
> The message still persists. I guess it stems from this entry:
> 
> https://github.com/OpenSlides/openslides-auth-service/blob/b77e9a1dad1bf2a650f6353f2a8583c5e102e98b/auth/libraries/pip-auth/setup.py#L21

Yeah, it corresponds to the entries in `setup.py`, which dependencies are needed.
